### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by Chris2011** [nikhilk/node-tensorflow#13]
I only want to know, whether the project is still alive or not.

Regards

Chris

**Comment by somombo** [comment]
I found nikhilk.net@gmail.com on @nikhilk's website  perhaps he would better be able to respond to email? Let us know

**Comment by Chris2011** [comment]
Ok thx, will try that :)

**Comment by nikhilk** [comment]
I am sorry I didn't respond to this in timely manner.

The project was on hold obviously with no cycles available to dedicate to this front... and as I look ahead, I think I would focus this project a bit more on using TensorFlow models in prediction via node.js, rather than training. There is significant logic in the TensorFlow python libraries around graph construction and training that would be futile effort to port and keep up-to-date. Instead the goal would be to load and use a trained and saved model.

Let me know if this interests you Chris and any other folks.

I hope to get some time during the break in couple of weeks to update things and set it up for future work. I might look at how I might bring this together along with my TensorLab (https://github.com/tensorlab) work.

**Comment by nikhilk** [comment]
I'll go ahead and close this out, but want to note that first round of revamp is done.

More work ahead, but as noted this module will focus on using graphs and models for prediction, rather than on training where the functionality in current Python APIs is both a must and hard to replicate.
